name: pip_quickstart
version: "1.0.0"
author: Levichev Dmitry <levichev.dmitry@gmail.com>
description: Quick start for Pip.Services toolkit on Dart
homepage: http://pipservices.org

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pip_services3_commons: ^1.1.4
  pip_services3_components: ^1.1.2
  pip_services3_rpc: ^1.1.2
  pip_services3_container: ^1.1.1
  shelf: ^1.2.0

dev_dependencies:
  test: ^1.17.12